python train_bnn.py --output_path ./output \
                    --data_path_train ./data_train.npy \
                    --data_path_test ./data_test.npy \
                    --data_path_val ./data_validate.npy \
                    --lr 0.001 \
                    --batch_size 1024 \
                    --epochs 100 \
                    --layers 256 168 64 8 \
                    --activation_inner 'tanh' \
                    --n_monte 50 \
                    --train_size 600000 \
                    --val_size 200000 \
                    --test_size 100000 \
                    --save_weights_iter 10 \
                    --target resp \
                    --mode bayesian
